import { createHash } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { SCHEMA_DIR, schemaFiles } from "../config/jsonschema.ts";
import { fromRoot, resolveModel, type Workspace } from "../config/load.ts";
import type { Role } from "../config/schema.ts";
import { memorySection } from "../core/memory.ts";
import { fail } from "../util/log.ts";

const MANIFEST = ".harness/sync.json";
const BANNER = "<!-- Generated by `harness sync` from roles/. Edit the YAML, not this file. -->";

interface Manifest {
  /** relative path -> sha256 of the content harness last wrote */
  files: Record<string, string>;
}

const sha256 = (s: string) => createHash("sha256").update(s).digest("hex");
const posix = (p: string) => p.split("\\").join("/");

async function readManifest(root: string): Promise<Manifest> {
  try {
    return JSON.parse(await readFile(join(root, MANIFEST), "utf8")) as Manifest;
  } catch {
    return { files: {} };
  }
}

function teamSection(ws: Workspace, role: Role): string | null {
  if (role.team.length === 0) return null;

  const lines = ["## Your team", "", "You can delegate to these subagents with the `task` tool:", ""];
  for (const name of role.team) {
    const member = ws.roles.get(name);
    if (!member) fail(`Role "${role.name}": unknown teammate "${name}"`);
    lines.push(`- \`${name}\` — ${member.description}`);
  }
  lines.push(
    "",
    "Delegate what is self-contained and verifiable, with a complete brief: a subagent",
    "cannot see your conversation. Do not delegate what you would do faster yourself, and",
    "never delegate the final call — that one is yours.",
  );
  return lines.join("\n");
}

/** Assembles the role prompt, its instruction files, its team, its memory and its output contract. */
export async function buildSystemPrompt(ws: Workspace, role: Role): Promise<string> {
  const sections: string[] = [role.prompt.trim()];

  for (const path of role.instructions) {
    const file = fromRoot(ws.root, path);
    let content: string;
    try {
      content = await readFile(file, "utf8");
    } catch {
      fail(`Role "${role.name}": missing instructions file: ${path}`);
    }
    sections.push(`## Reference: ${path}\n\n${content.trim()}`);
  }

  const team = teamSection(ws, role);
  if (team) sections.push(team);

  const memory = await memorySection(ws, role);
  if (memory) sections.push(memory);

  if (role.outputs.length > 0) {
    const list = role.outputs.map((output) => `- \`${output}\``).join("\n");
    sections.push(
      `## Deliverables\n\nBefore you finish, these files must exist and be up to date:\n\n${list}\n\n` +
        `Write them yourself; do not describe their contents in chat and stop there.`,
    );
  }

  return sections.join("\n\n");
}

function agentEntry(ws: Workspace, role: Role, promptFile: string): Record<string, unknown> {
  const entry: Record<string, unknown> = {
    description: role.description,
    mode: role.mode,
    model: resolveModel(ws.config, role.model),
    // opencode resolves {file:...} relative to the project root.
    prompt: `{file:./${posix(relative(ws.root, promptFile))}}`,
  };

  const temperature = role.temperature ?? ws.config.defaults.temperature;
  if (temperature !== undefined) entry.temperature = temperature;

  const tools = { ...ws.config.defaults.tools, ...role.tools };
  if (Object.keys(tools).length > 0) entry.tools = tools;

  const permission = { ...ws.config.defaults.permission, ...role.permission };
  if (Object.keys(permission).length > 0) entry.permission = permission;

  return entry;
}

export interface Generated {
  /** absolute path -> content */
  files: Map<string, string>;
}

/** Everything harness owns: opencode.json, one prompt per role, and the editor schemas. */
export async function generate(ws: Workspace): Promise<Generated> {
  const files = new Map<string, string>();
  const promptDir = fromRoot(ws.root, ws.config.paths.prompts);
  const agents: Record<string, unknown> = {};

  for (const role of [...ws.roles.values()].sort((a, b) => a.name.localeCompare(b.name))) {
    if (role.disabled) continue;
    const promptFile = join(promptDir, `${role.name}.md`);
    files.set(promptFile, `${BANNER}\n\n${await buildSystemPrompt(ws, role)}\n`);
    agents[role.name] = agentEntry(ws, role, promptFile);
  }

  const config: Record<string, unknown> = {
    $schema: "https://opencode.ai/config.json",
    model: resolveModel(ws.config, undefined),
  };
  if (ws.config.instructions.length > 0) config.instructions = ws.config.instructions;
  if (ws.config.defaults.permission && Object.keys(ws.config.defaults.permission).length > 0) {
    config.permission = ws.config.defaults.permission;
  }
  if (Object.keys(ws.config.provider).length > 0) config.provider = ws.config.provider;
  if (Object.keys(ws.config.mcp).length > 0) config.mcp = ws.config.mcp;
  config.agent = agents;

  files.set(fromRoot(ws.root, ws.config.paths.opencodeConfig), `${JSON.stringify(config, null, 2)}\n`);

  // JSON Schemas for the YAML files, so the editor validates against our definitions
  // instead of guessing from the file name.
  for (const [name, content] of Object.entries(schemaFiles())) {
    files.set(join(ws.root, SCHEMA_DIR, name), content);
  }

  return { files };
}

export interface SyncResult {
  written: string[];
  unchanged: string[];
  /** Files edited by hand since the last sync — never overwritten without --force. */
  drifted: string[];
  removed: string[];
}

/**
 * Writes what `generate` produced. Content harness did not write itself is treated as
 * drift and left alone unless `force` is set.
 */
export async function sync(
  ws: Workspace,
  opts: { force?: boolean; check?: boolean } = {},
): Promise<SyncResult> {
  const { files: targets } = await generate(ws);
  const manifest = await readManifest(ws.root);
  const result: SyncResult = { written: [], unchanged: [], drifted: [], removed: [] };
  const nextFiles: Record<string, string> = {};

  for (const [file, content] of targets) {
    const rel = relative(ws.root, file);
    const current = await readFile(file, "utf8").catch(() => null);

    if (current === content) {
      result.unchanged.push(rel);
      nextFiles[rel] = sha256(content);
      continue;
    }
    // Different content than we would write: either hand-edited since the last sync, or
    // a pre-existing file harness has never owned. Both are left alone without --force.
    const known = manifest.files[rel];
    const isOurs = known !== undefined && known === sha256(current ?? "");
    if (current !== null && !isOurs && !opts.force) {
      result.drifted.push(rel);
      if (known !== undefined) nextFiles[rel] = known;
      continue;
    }

    result.written.push(rel);
    nextFiles[rel] = sha256(content);
    if (!opts.check) {
      await mkdir(dirname(file), { recursive: true });
      await writeFile(file, content, "utf8");
    }
  }

  // Files we used to own and no longer generate: deleted roles, and artefacts of previous
  // versions. Only removed when untouched since we wrote them.
  for (const [rel, hash] of Object.entries(manifest.files)) {
    if (nextFiles[rel]) continue;
    const file = join(ws.root, rel);
    const current = await readFile(file, "utf8").catch(() => null);
    if (current === null) continue;
    if (sha256(current) !== hash) {
      result.drifted.push(rel);
      nextFiles[rel] = hash;
      continue;
    }
    result.removed.push(rel);
    if (!opts.check) await unlink(file);
  }

  if (!opts.check) {
    await mkdir(join(ws.root, ".harness"), { recursive: true });
    await writeFile(join(ws.root, MANIFEST), `${JSON.stringify({ files: nextFiles }, null, 2)}\n`, "utf8");
  }

  return result;
}
