import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { fromRoot, type Workspace } from "../config/load.ts";
import type { Role } from "../config/schema.ts";
import { log } from "../util/log.ts";

export interface MemoryEntry {
  name: string;
  description: string;
  type: string;
  file: string;
  body: string;
}

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;

export function memoryDir(ws: Workspace): string {
  return fromRoot(ws.root, ws.config.paths.memory);
}

export function indexPath(ws: Workspace): string {
  return join(memoryDir(ws), ws.config.memory.index);
}

export async function listMemories(ws: Workspace): Promise<MemoryEntry[]> {
  const dir = memoryDir(ws);
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }

  const memories: MemoryEntry[] = [];
  for (const entry of entries.sort()) {
    if (extname(entry) !== ".md" || entry === ws.config.memory.index) continue;
    const file = join(dir, entry);
    const raw = await readFile(file, "utf8");
    const match = FRONTMATTER.exec(raw);

    // One malformed entry must not make the whole memory unreadable.
    let meta: Record<string, unknown> = {};
    if (match) {
      try {
        meta = (parseYaml(match[1] as string) ?? {}) as Record<string, unknown>;
      } catch {
        log.warn(`unreadable frontmatter in ${entry}, entry skipped`);
        continue;
      }
    }

    memories.push({
      name: String(meta.name ?? basename(entry, ".md")),
      description: String(meta.description ?? ""),
      type: String(meta.type ?? "note"),
      file,
      body: (match?.[2] ?? raw).trim(),
    });
  }
  return memories;
}

/**
 * The index is regenerated from the entries, never hand-maintained: an index that drifts
 * from the files is worse than no index, because agents trust it.
 */
export async function rebuildIndex(ws: Workspace): Promise<string> {
  const memories = await listMemories(ws);
  const byType = new Map<string, MemoryEntry[]>();
  for (const memory of memories) {
    byType.set(memory.type, [...(byType.get(memory.type) ?? []), memory]);
  }

  const lines = [
    `# Memory — ${ws.config.project.name}`,
    "",
    "Generated by `harness memory sync`. One line per entry; the detail lives in the file.",
    "",
  ];
  for (const [type, entries] of [...byType].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`## ${type}`, "");
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- [${entry.name}](./${basename(entry.file)}) — ${entry.description}`);
    }
    lines.push("");
  }
  if (memories.length === 0) lines.push("_No entries yet._", "");

  const content = `${lines.join("\n").trimEnd()}\n`;
  await mkdir(memoryDir(ws), { recursive: true });
  await writeFile(indexPath(ws), content, "utf8");
  return content;
}

export async function addMemory(
  ws: Workspace,
  entry: { name: string; description: string; type: string; body: string },
): Promise<string> {
  const file = join(memoryDir(ws), `${entry.name}.md`);
  // Serialised rather than concatenated: a description containing ":" or "#" would break
  // the frontmatter.
  const frontmatter = stringifyYaml({ name: entry.name, description: entry.description, type: entry.type });
  const content = `---\n${frontmatter}---\n\n${entry.body.trim()}\n`;

  await mkdir(memoryDir(ws), { recursive: true });
  await writeFile(file, content, "utf8");
  await rebuildIndex(ws);
  return file;
}

/**
 * The prompt section injected into every role that reads memory. Only the index goes in:
 * entries are read on demand, so memory can grow without inflating every single prompt.
 */
export async function memorySection(ws: Workspace, role: Role): Promise<string | null> {
  if (!ws.config.memory.enabled || role.memory === "none") return null;

  const memories = await listMemories(ws);
  const relative = ws.config.paths.memory.replace(/^\.\//, "");
  const lines = [
    "## Project memory",
    "",
    memories.length === 0
      ? `No entries yet (\`${relative}/\`).`
      : "What this project has already learned. Read the relevant file before reworking a topic listed here.",
    "",
  ];
  for (const memory of memories) {
    lines.push(`- \`${relative}/${basename(memory.file)}\` (${memory.type}) — ${memory.description}`);
  }

  if (role.memory === "write") {
    lines.push(
      "",
      "When you learn something durable — a convention of this project, a decision and its",
      `reason, a trap that cost time — add a file under \`${relative}/\` with this frontmatter:`,
      "",
      "```markdown",
      "---",
      "name: slug-in-kebab-case",
      "description: one line; this is what other roles will read",
      "type: convention | decision | failure | preference",
      "---",
      "",
      "The fact, and why it matters.",
      "```",
      "",
      "Do not record what the code or the git history already says.",
    );
  }
  return lines.join("\n");
}
